[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001CBE8683650>: Failed to resolve 'selenium' ([Errno 11001] getaddrinfo failed)")': /session
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001CBE8682550>: Failed to resolve 'selenium' ([Errno 11001] getaddrinfo failed)")': /session
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001CBE8682150>: Failed to resolve 'selenium' ([Errno 11001] getaddrinfo failed)")': /session